name: "Packer checks"
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths:
      - "images/**"
      - ".github/workflows/packer-build.yml"

env:  
  AWS_REGION: eu-west-1

jobs:
  verify_packer:
    name: Verify packer    
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:1.7.8
    defaults:
      run:
        working-directory: images/linux-amzn2
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: packer init
        run: packer init .

      - name: check terraform formatting
        run: packer fmt -recursive -check=true .        

      - name: packer validate
        run: packer validate .
