name: "Terraform checks"
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths-ignore:
      - "modules/*/lambdas/**"

env:
  tf_version: "1.0."
  tf_working_dir: "."
  AWS_REGION: eu-west-1
jobs:
  verify_module:
    name: Verify module
    strategy:
      matrix:
        terraform: [1.0.8]
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.1.0
      - name: "Fake zip files" # Validate will fail if it cannot find the zip files
        run: |
          touch modules/webhook/lambdas/webhook/webhook.zip
          touch modules/runners/lambdas/runners/runners.zip
          touch modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/runner-binaries-syncer.zip
      - name: terraform init
        run: terraform init -get -backend=false -input=false
      - name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
        continue-on-error: true
      - name: validate terraform
        run: terraform validate

  verify_examples:
    name: Verify examples
    strategy:
      fail-fast: false
      matrix:
        terraform: [0.14.3, 0.15.5, 1.0.8]
        example: ["default", "ubuntu", "prebuilt"]
    defaults:
      run:
        working-directory: examples/${{ matrix.example }}
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - uses: actions/checkout@v3.1.0
      - name: terraform init
        run: terraform init -get -backend=false -input=false
      - if: contains(matrix.terraform, '1.0.')
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
        continue-on-error: true
      - name: validate terraform
        run: terraform validate
